default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: '<%= ENV['DATABASE_PASSWORD'] %>'

development:
  <<: *default
  database: Hello_Rails_development

test:
  <<: *default
  database: Hello_Rails_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
